apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: iac-proxy-deployment-vs
  labels:
     labels:
      app:  iac-proxy-deployment-vs
      chart:  iac-proxy-deployment-vs
      release: iac-proxy-deployment-vs
      version: 1.0.0
spec:
  hosts:
    - "*"
  gateways:
    - istio-system/istio-gateway
  tcp:
  - match:
    - port: 8888
    route:
    - destination:
        host: iac-proxy-deployment-service.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8888
