apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-proxy-deployment
  labels:
    app: iac-proxy-deployment
    chart: iac-proxy-deployment
    release: iac-proxy-deployment
    version: 1.0.0
    deployment-type: api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iac-proxy-deployment
  template:
    metadata:
      name: iac-proxy-deployment
      labels:
        app: iac-proxy-deployment
        chart: iac-proxy-deployment
        release: iac-proxy-deployment
        pod-type: api
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: iac-proxy-deployment
        image: yegor256/squid-proxy:sha-4b1725e@sha256:fe97386361b185bc9493abeb28bbc5b15ed68e0f18cf91e0248af5251bbbb6d1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            memory: 4096Mi
            cpu: "2"
          requests:
            memory: 2048Mi
            cpu: "1"
        ports:
        - containerPort: 8888
        env:
        - name: USERNAME
          value: user
        - name: PASSWORD
          value: pass
        
