apiVersion: v1
kind: Service
metadata:
  name: iac-proxy-deployment-service
  labels:
    app: iac-proxy-deployment-service
    chart: iac-proxy-deployment-service
    release: iac-proxy-deployment-service
    version: 1.0.0
spec:
  ports:
    # the port that this service should serve on
  - protocol: TCP
    port: 3128
    targetPort: 3128
  selector:
    app: iac-proxy-deployment
    release: iac-proxy-deployment
    pod-type: api
  type: "NodePort"
